[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200